### ISSUE TITLE
When upgrading to supergroup, group is not updated in database

### ISSUE THREAD

**Issue by parabola949** [GreyWolfDev/Werewolf#12]
When a group is upgraded, it gets a new id.  in the database, the group becomes a new row, and stats are essentially lost, as well as all settings.  Need to detect the upgrade and change the id

**Comment by TheZeus121** [comment]
To detect the upgrade maybe the migrate_to_chat_id in Message object might be useful. https://core.telegram.org/bots/api#message

**Comment by JuanPotato** [comment]
Still a bug
