### ISSUE TITLE
[Feature request] Extend joining time command

### ISSUE THREAD

**Issue by renyhp** [GreyWolfDev/Werewolf#14]
Adding a command like `/extend <seconds>` to extend time to join the game could be useful for small groups in which not always there are enough players online, also because by `/flee /join` the joining time left could increase to 1 minute at most.

**Comment by BladeZero** [comment]
Has been developed. Awaiting code review.

**Comment by parabola949** [comment]
I would assign to BladeZero, but he is not a contributor (yet...?)
I'm letting him work on this one, as he pointed out it's a good way to learn the bot.
BladeZero - Let's make this configurable.  When you have some time, let me know, I'll get the field added to the database and update the entities so you can use it.

**Comment by Olgabrezel** [comment]
I think this issue should be closed :D

**Comment by renyhp** [comment]
Yes it should! I forgot to. Thanks!

**Comment by Olgabrezel** [comment]
I thought, you'd study XD

**Comment by renyhp** [comment]
Sure, but I still receive emails :P
