### ISSUE TITLE
Lynch voting should be secret (optionally)

### ISSUE THREAD

**Issue by Jean1995** [GreyWolfDev/Werewolf#16]
We think that it woud be nice to have opportunity to set the lynch voting to be secret.
This could avoid "tactical voting", e.g. forcing draws etc.
(Should be optional though, because one could like this way of tactical voting)

**Comment by parabola949** [comment]
There are options for this planned - hide all votes (never show), show vote counts at end, show votes as they happen, etc etc etc.

**Comment by Eldinnie** [comment]
I would like to add show votes at the end (not only counts) but keeping it secret during voting

**Comment by NachoCozza** [comment]
@Jean1995  That's a great idea!

**Comment by parabola949** [comment]
Added in beta.  Will be available in master soon
