### ISSUE TITLE
Players can still join two games at once

### ISSUE THREAD

**Issue by renyhp** [GreyWolfDev/Werewolf#198]
Despite commit 55d677e7, players can still join two games.
I joined a second game while my first game was in joining phase, and no problem arose. Then I tried joining a second game while I was actually playing the first one, and I could still do it.

**Comment by SilasSit** [comment]
I do want to play two or more games in parallel, but I think what need to be fixed is the sticky buttons that can't be pressed when multiple games are running

**Comment by SilasSit** [comment]
For now I can't start but join when another game is already running

**Comment by Olgabrezel** [comment]
Now they can't join multiple games anymore.
