### ISSUE TITLE
Cult died from visiting a wolf who did not stay home

### ISSUE THREAD

**Issue by renyhp** [GreyWolfDev/Werewolf#206]
At first night, Wolf Cub chose Drunk and Cult chose Wolf Cub. Drunk died regularly, but Cult died from visiting the Wolf.

**Comment by Olfi01** [comment]
As far as I can tell, this is fixed by now.

**Comment by Olgabrezel** [comment]
I'll close this, I haven't heard of it again and many changes were done since * shrug *
