### ISSUE TITLE
JSON response for /Stats/*

### ISSUE THREAD

**Issue by badgercl** [GreyWolfDev/Werewolf#207]
Hi,

It would be possible allow the _Werewolf for Telegram/Werewolf Website/Controllers/StatsController.cs_ file to provide JSON responses in addition to the HTML table?

I think it could be done by adding the type=json parameter to the GET call and default to HTML when not provided.

I would love to offer the pull request myself but I do not have any knowledge of .NET nor have a Windows machine.

Thanks in advance!

**Comment by Olfi01** [comment]
I know this Issue was queued long ago, but would it help you to get the table as a string in html code? There is already a method for that at http://www.tgwerewolf.com/Stats/PlayerStats?pid={playerid}.
About the JSON-Response, I'm looking into it, but don't expect too much, I'm new to ASP.Net.

**Comment by Olfi01** [comment]
Found a solution, coding it rn. Let's hope the PR will be merged.

**Comment by Olfi01** [comment]
#252 
I finished right now

**Comment by badgercl** [comment]
Cool, thanks for the PR, I'll subscribe to it to try it when it goes live 👍

**Comment by renyhp** [comment]
The PR was merged a bit ago.
