### ISSUE TITLE
Gunner should have a percentage chance to shoot wrong target

### ISSUE THREAD

**Issue by TonyRoomZ** [GreyWolfDev/Werewolf#208]
Since we have clumsy, and the hunter has a percentage change to kill a wolf when attacked,  it would make sense (and should be possibly toggled) that a gunner has a percentage change to either shoot themselves or the wrong target.  This shouldn't be a new role. Just an option onto the exsiting one.  Call it distracted or backfired?

**Comment by renyhp** [comment]
I don't think we're changing how the gunner works. However, you can post in #141 to make a suggestion for a new role :)
