### ISSUE TITLE
Doppelganger converts to two roles same time

### ISSUE THREAD

**Issue by Olgabrezel** [GreyWolfDev/Werewolf#209]
In one game, I was doppelganger of Player A. Player A was villager, Player B was alpha, all the other players were dead. Player B infected me at night and reveald himself as alpha so we could lynch Player A together and win. We lynched Player A and I got a privat message, I convrrted to wolf because I was bitten, and another message, I would (now) be a villager, because my role model Player A had died. Anyway, I won the game as a wolf together with Player B. But the message that I'd be vg now was very confusing and false.

**Comment by Olfi01** [comment]
you first transformed into a vg because player a died. then the night fell and you transformed into ww 'cause the alpha bit you. there's nothing wrong with that.

**Comment by Olgabrezel** [comment]
@Olfi01 There us something wrong. It is 

1) confusing, even if you are right, this is correct

2) wrong, vecause I got the message that I cobvert to wolf BEFORE the message I convert to vg. And this would mean, as a wolf, I suddenly convert to vg.

**Comment by Olfi01** [comment]
Well your second point really is a problem... but it could be solved by moving the "was I converted by Alpha" Check before the "did my role model die" check. But... were you werewolf or vg afterwards? 'cause if you were vg, I guess it's a problem with the Telegram api and can't be fixed by the developers of this code

**Comment by Olgabrezel** [comment]
Just read the issue I wrote before you comment:

"Anyway, I won the game as a wolf together with Player B."

This should answer your question. And you don't have to tell me that it could be fixed like that, I know it, that's why I created a issue here.

I have actually no idea why you could think it is the bot API, but please, let's talk about that in private and not in GitHub.
