### ISSUE TITLE
[Bug] Wild child doesn't become Werewolf

### ISSUE THREAD

**Issue by Greaka** [GreyWolfDev/Werewolf#212]
When a wild child selects the only werewolf and the armor couples the werewolf with the first victim of the werewolf, the wild child doesn't become werewolf and the game ends.

example: today, 17:32 german time at group -118107563

**Comment by Olgabrezel** [comment]
Always the same: if a player dies because of his lover's death, wild child and doppelgänger don't transform if their role model was that player.

**Comment by Greaka** [comment]
To clarify:
1. wc selects ww
2. armor couples ww with player42
3. ww kills player42
4. game ends

wc should have become ww. instead the game ended

**Comment by Olgabrezel** [comment]
Yes exactly, this is what I said - The rolemodel of the wild child died out of love, and when this happens, wc and Doppel don't transform. Check #237 , this would solve it. By checking whether someone should transform at that point, before letting the game end.
