### ISSUE TITLE
Amor. Bot not responding. Voting for own death and already dead people to lynch

### ISSUE THREAD

**Issue by Rumsti** [GreyWolfDev/Werewolf#213]
JPB:
If the bot is not responding when choosing a lover as Amor it is possible to vote for your own death.  Forthermore, it is possible to vote for a dead player to be killed too.

Werewolf Moderator:
JPB wählte JPB!

**Comment by renyhp** [comment]
Unfortunately, we can't control what happens when the bot is not responding. This kind of issue are possible to encounter in that case. We always suggest to stop using the bot when it doesn't respond correctly, so that it can recover properly.
