### ISSUE TITLE
Hunter and Two Lovers -Hunter doesn't get a chance to shoot

### ISSUE THREAD

**Issue by RainRat** [GreyWolfDev/Werewolf#221]
Scenario:

Hunter and two Lovers(one Wolf, and one Villager team) are left. Hunter killed at night. Game immediately goes to Lover victory without giving Hunter a chance to shoot.

**Comment by renyhp** [comment]
When the hunter is killed by the wolves, they are not asked for who to shoot. Instead, in the case of lone wolf, they will kill the wolf at 30% chance, or otherwise they will die.
