### ISSUE TITLE
[BuG] Some time it Doesn't respond users & Admins Command..

### ISSUE THREAD

**Issue by kuck7610** [GreyWolfDev/Werewolf#234]
1. Some time it not responding like at a time 5-6 use trying to join the game but on that time... 1-2 person can't join it... 
2. Some time admin trying to force start game but Bot wasn't responding...

**Comment by abdumuhaimin** [comment]
same issue here. it happens quite a number of times now

**Comment by renyhp** [comment]
That is not a bot issue, or at least, it is not a bug due to some wrong code. Sometimes the bot has too many users connected at the same time and it lags because of Telegram API limits. Not something we can fix
