### ISSUE TITLE
Sk / Gunner ending

### ISSUE THREAD

**Issue by Olfi01** [GreyWolfDev/Werewolf#235]
Shouldn't there be a special ending if sk and Gunner are left and Gunner still has bullets?

**Comment by Olgabrezel** [comment]
But... what? 

Everyone dead? Then the sk/hunter thing wouldn't be special anymore. 
Random who survives and who not? In my opinion too similar to wolf/hunter ending...

**Comment by Olfi01** [comment]
Well, I dunno, just wanted to state it. Just a normal ending seems wrong to me.

**Comment by renyhp** [comment]
There are multiple reasons why not. Lorewise, the serial killer is very crazy, and the only one who has a similar paranoia is the hunter; the gunner doesn't. Also, speaking about balance, this would make the gunner more similar to a hunter, but then it would be just a stronger hunter... which is not what we want to achieve.
