### ISSUE TITLE
Most common role

### ISSUE THREAD

**Issue by Olfi01** [GreyWolfDev/Werewolf#236]
Wouldn't it be better to make the "most common role" thingy the role that the player had relative to the average appearance of that role? Like, player role count divided by total role count?

**Comment by Olgabrezel** [comment]
I like #199 the most: the role the player most commonly wins in. If someone is really good as a tanner, there is tanner in his stats, instead of the always same "Mason", "Villager", "Villager", "Mason", .....

**Comment by Olfi01** [comment]
You mean in percentage of the role? That'd be great too

**Comment by Olgabrezel** [comment]
Yes exactly. Like a player has 5 games in his history:

Wolf - Won
Wolf - Won
Mason - Won
Mason - Won
Mason - Lost

Currently, their role would be 
mason (60% of all games mason), 

with the change that m-----r suggests, it would be 
wolf (won 100% of their wolf games but only 66% of their mason games).

If you support that, you can close this issue cause it already exists ( #199 )
