### ISSUE TITLE
English.xml

### ISSUE THREAD

**Issue by MrkAi18** [GreyWolfDev/Werewolf#241]
<<<<<<< HEAD
    <value>You get to have fun! Each day, you will attempt to decieve your fellow players. However, each night, you will get to pick a player to kill!\nNote: If you attack the cursed, they will become a wolf like yourself! Hooray friends!\nIf you attack the drunk, you yourself will become drunk, and will be unable to do the next attack as you sleep off your hangover! (Usually, this means you can't attack the following night, but if the Wolf Cub was killed and the Drunk was your first choice, you won't be able to kill the second player, and you will still be able to attack the following night.) </value>
=======
    <value>You get to have fun! Each day, you will attempt to decieve your fellow players. However, each night, you will get to pick a player to kill!\nNote: If you attack the cursed, they will become a wolf like yourself! Hooray friends!\nIf you attack the drunk, you yourself will become drunk, and will be unable to do the next attack as you sleep off your hangover! (Usually, this means you can't attack the following night, but if the Wolf Cub was killed and the Drunk was your first choice, you won't be able to kill the second player, an you will still be able to attack the following night.) </value>
>>>>>>> 61cdd6623e3861f9f7214d4bf85603079a7135cf

git fetch problem?

**Comment by parabola949** [comment]
Quite.  One moment, fixing it.

**Comment by parabola949** [comment]
It's fine in the beta branch, which means the file on the server is also fine now.  Will be patched in master as soon as we merge.
