### ISSUE TITLE
[Role suggest] Sheriff

### ISSUE THREAD

**Issue by gloomy-ghost** [GreyWolfDev/Werewolf#243]
> This card is given to a player in more than his card. He is elected by a vote. This player's vote count for 2 instead of 1. If He dies, he will decide who will be the next Sheriff.  -- [Wikipedia](https://en.wikipedia.org/wiki/The_Werewolves_of_Millers_Hollow#Sheriff)

In addiction, there should be an option that the sheriff can perfer not passing the role to anyone when he is killed.

**Comment by Olgabrezel** [comment]
Please don't make issues for role requests but comment them to issue #141 :)
