### ISSUE TITLE
GreyWolfEnforcer: /kick returns system message instead of username

### ISSUE THREAD

**Issue by crtrue** [GreyWolfDev/Werewolf#246]
Command: 
Tiny Lord:
/kick @Dark_mind

Message: 
Grey Wolf Enforcer:
System.Threading.Tasks.Task`1[StackExchange.Redis.RedisValue] (3194426) has been kicked by Daniel (58249866).

**Comment by renyhp** [comment]
If this bug wasn't solved yet, please go to @werewolfsupport. This is the @werewolfbot repo - nothing to do with @enforcerbot.
