### ISSUE TITLE
Extend time should be parametrized

### ISSUE THREAD

**Issue by MarAvFe** [GreyWolfDev/Werewolf#253]
It could be enabled another couple of commands like ```/extendMore``` or ```/extendLess``` to define how much the admin want to extend the joining time. Less being 30s, normal 1min and More 2min

Another solution could be some parameter like ```/extendX``` with the X being some number of minutes to wait, so the admin can call ```/startgame``` and then ```/extend5``` to give the players 5 minutes to join. Defining some range from 1-10 could be nice if you want to avoid /extend99.

This enhancement is because our group sometimes wants to give more than 30s and our admin hits ```/extend``` like 10-15 times. I think this could save a lot of requests.

**Comment by renyhp** [comment]
You can already extend the time by x seconds by using `/extend x`.
