### ISSUE TITLE
/nextgame no notif

### ISSUE THREAD

**Issue by Alexstraza3105** [GreyWolfDev/Werewolf#262]
Hai there, so I recently used the /nextgame feature of ww mod beta in amnies. I received the notif that I am in the waitlist. But then when the next game started, I did not get the notif. Is this a bug? 

*p.s. i had started the bot long, long ago. Just in case lol. I'm not a new player

**Comment by renyhp** [comment]
Does that still happen?

**Comment by Olfi01** [comment]
This should definitely not happen any more.

**Comment by Olgabrezel** [comment]
It does, but that can't be fixed.

The thing is, if you use the /nextgame command WHILE a game is currently in join phase, you will be added to the list. But when the game starts, it empties the list for the whole group. So, the solution is to just not use /nextgame while a game is in join phase.
