### ISSUE TITLE
Stats: achievements api not showing new ones

### ISSUE THREAD

**Issue by badgercl** [GreyWolfDev/Werewolf#266]
Hi,

I'm consuming the http://www.tgwerewolf.com/Stats/PlayerAchievements/?pid=PID endpoint to gather and process users achievements. I've just noticed it's not including the new achievements. For instance, I got the "President" achievement:
<img width="439" alt="screen shot 2017-05-24 at 2 43 11 pm" src="https://cloud.githubusercontent.com/assets/4398862/26419996/6e2db0f0-408f-11e7-81a2-0245e484ab44.png">
But it does not appear on the stats page nor it's sent by calling the API.

Please update the website to be able to check the new achievements. 

Thanks! 🐺

**Comment by renyhp** [comment]
This, as far as I remember, has been fixed.
