### ISSUE TITLE
Probably doing something wrong - help pl0x

### ISSUE THREAD

**Issue by Vortex20000** [GreyWolfDev/Werewolf#272]
Hey, I followed the instructions to set this up in README.md and dealt with it expecting _BotConnectionString_ in the registry and all that...

I suspect the issue I'm having has something to do with my SQL authentication. Here's what it looks like in SQL Management Studio '17: http://i.imgur.com/qX3lE1R.png

My string for connection: `metadata=res://*/WerewolfModel.csdl|res://*/WerewolfModel.ssdl|res://*/WerewolfModel.msl;provider=System.Data.SqlClient;provider connection string="data source=DESKTOP-7CAT163\SQLEXPRESS;initial catalog=werewolf;user id=DESKTOP-7CAT163\anaki;Trusted_Connection=True;MultipleActiveResultSets=True;App=EntityFramework"`

Full debug output in VisStudio17 (community): https://pastebin.com/p72rJeeg

---------
Program breaks at this specific line in Werewolf_Control/Helpers/Bot.cs:
`var b = db.BotStatus.Find(id);`

Running Win10, MS SQL Server Express (v11), Visual Studio 17 Community; have .NET frameworks up till 4.7 and all the other dependencies... I think.

**Comment by Olfi01** [comment]
The readme.md is not up-to-date any more, as is the sql script for the DB setup.

**Comment by Olgabrezel** [comment]
Though now the SQL-Script is up-to-date, so this exact error shouldn't happen anymore :D
