### ISSUE TITLE
Option to remove harlot

### ISSUE THREAD

**Issue by tokyodrill** [GreyWolfDev/Werewolf#276]
can someone add the option to remove harlot plss, i am not familiar in coding so i cant do it myself, thanks
the reason is because i found harlot to be an inappropriate role since im playing with children

**Comment by renyhp** [comment]
There is a plan to make a kid-friendly version of the game. Please go to @werewolfsupport on Telegram if you want to collaborate. Meanwhile, maybe you can use the English SFW version.
