### ISSUE TITLE
Cupid can choose him/herself.

### ISSUE THREAD

**Issue by pavelonsky** [GreyWolfDev/Werewolf#278]
I've seen an in a few games that Cupid selects him/herself and other to become Lovers, as a strategy to win as Lovers. I believe this is a strategy not cool and should be fixed. The player as Cupid should not appear as an option for Lovers. Philosophically Cupid cannot be in love, and Physically one cannot arrow him/herself, so, it makes sense he/her cannot be one of the Lovers.

**Comment by crtrue** [comment]
I also believe it is rare for werewolves to eat Cupid as well. I also don't see why Cupid couldn't just take one of his arrows and jab himself with it. That said, I consider it a valid strategy. Cupid takes on the risk of dying easier for a "friend". 

My only complaint about Cupid is that after the initial turn, it's basically just a villager at that point.

**Comment by pavelonsky** [comment]
So you believe Cupid is allowed to jab himself and fall in love with another. Fair point. I think he shouldn't, he should select other two players and then he just becomes a villager. In the matter of werewolves eating Cupid, I concur in that a Cupid is a saint entity, so after selecting, he should be saved against Werewolves, as though he was saved by a Guardian Angel, he is kind of an angel anyways, but not Serial Killers or Lynching. That makes sense.

**Comment by Olgabrezel** [comment]
There is even an achievement

> Self loving
> As the cupid, choose yourself as a lover

for that case. Also, one can arrow him/herself by shooting straight in the air. Finally, there is maximum one cupid per game and therefore maximum 2 lovers, so being a lover is rare and if you're already cupid it's likeky that you want to be lover and have higher win chances.

**Comment by Olgabrezel** [comment]
And the cupid to be unable to die from wolves doesn't make really sense either, if you don't have a sk, they would be a villager that can't be killed at night, which is way too op
