### ISSUE TITLE
Fix lovers' win condition

### ISSUE THREAD

**Issue by Niranufoti** [GreyWolfDev/Werewolf#279]
Currently, the lovers win if either lover wins, even if they are a villager-wolf couple that died, leading to a village victory. This creates situations where, on a rule level, it would be perfectly sensible for a player to lynch their lover (leading to all players winning). That cannot be intended behavior.
Additionally, if the lovers are both e.g. villagers and are the only players left, the game ends in lover victory, with the rest of the village losing. That does not seem sensible, as this can turn two perfectly innocent players against the rest of their team.

My fix for both of these problems is to change the win conditions:
- If (and only if) the lovers are part of the same team (e.g. village, wolves, cult), they simply win or lose with their team – even if they are the sole survivors, and even if they are dead.
- Otherwise, i.e. if they are of different teams, they win if they survive (and there isn't another win condition, e.g. Tanner). This would include e.g. a villager-wolf couple among other wolves.
- As a possible change (maybe a group setting) to encourage lovers talking to each other, the second case could be changed to "if your lover loses, you lose too" (as opposed to the current "if your lover wins, you win too"). This would mean that a player would have to help their DG lover to kill their target, or their Tanner lover to get lynched. This would however necessitate a special treatment of a DG who's in love with their target.

**Comment by Olfi01** [comment]
I think it's fine the way it is...

**Comment by parabola949** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[Werewolf] Fix lovers winning condition to make them like we discussed](https://trello.com/c/4s16Vbco/6-werewolf-fix-lovers-winning-condition-to-make-them-like-we-discussed)

**Comment by whosdudab** [comment]
i think it's fine the way it is too, just wanted cupid to be included in the love team. 
Cupid could be both village and love.

**Comment by Olgabrezel** [comment]
> i think it's fine the way it is too, just wanted cupid to be included in the love team.
Cupid could be both village and love.

We are going to do this. For the special lovers ending, Cupid will win as well. :)
