### ISSUE TITLE
Suggestion: All-at-once voting mode (name WIP)

### ISSUE THREAD

**Issue by Evandill** [GreyWolfDev/Werewolf#280]
A mode where the bot holds all the votes and just reveals them all at once once everyone has voted and the person who should die has died.  it simultaneously prevents bandwagoning on rando lynches and holds the less trustworthy accountable. only issue is that it could be quite a little spammy in bigger games with a giant vote list in one message.

**Comment by Olgabrezel** [comment]
This has been implemented (currently only in beta) as `Secret Lynch` enabled + `Secret: Vote Counts` enabled + `Secret: Voters` enabled. Closing this issue :)
