### ISSUE TITLE
Unable to choose second options as Cupid

### ISSUE THREAD

**Issue by aizen-rish** [GreyWolfDev/Werewolf#282]
The bot always ignore the second option to choose , example like choosing the second lover as cupid, or second kill as wolf, when u have 2 kills (cub died). The second choices are just ignored, and the game moves on.

**Comment by renyhp** [comment]
Was that caused by lag? The code does handle the second choices and, in my experience, they are taken into account.

**Comment by aizen-rish** [comment]
It definitely wasn't as the Night phase ends as soon as I chose the first choice in the respective roles, even when there was enough time left for the night phase. 
Also there is no issue in choosing the first choice , so i t's probably not lag what caused this.

**Comment by renyhp** [comment]
So are you saying that happened just once? Not "always"?

**Comment by Olgabrezel** [comment]
Closing this in favor of #312. Also not sure if the bug still exists, I haven't heard of it in a rather long time
