### ISSUE TITLE
Allow self-voting

### ISSUE THREAD

**Issue by Niranufoti** [GreyWolfDev/Werewolf#285]
Occasionally, a player might want to vote for themselves during the lynch cycle – maybe to balance out another's vote so that nobody is lynched, or maybe because they want to die for whatever reason.
Since normally, players won't self-vote unless they have a good reason to, I don't see a good reason to forbid them from doing so when they want to.

**Comment by parabola949** [comment]
Because then the tanner would always vote for himself
