### ISSUE TITLE
Node encounters exception

### ISSUE THREAD

**Issue by HellScre4m** [GreyWolfDev/Werewolf#288]
Hi
`
Unhandled Exception: System.NullReferenceException: Object reference not set to
an instance of an object.
   at Werewolf_Node.Program.Main(String[] args) in G:\Test\Werewolf\Werewolf for
 Telegram\Werewolf Node\Program.cs:line 80
`
I'm certain right keys are at the right place (HKEY_LOCAL_MACHINE\SOFTWARE\Werewolf). Also Control runs with no problems, till it manages to run Node.
Please help me with this just put 24 hours of my time on running the bot ...
I'm running this on an x86 machine.
Many thanks

**Comment by SilasSit** [comment]
Is it the aToken? You can uncomment it if you don't need it

**Comment by HellScre4m** [comment]
Yeah I hardly embedded token inside of the code. DotNet bug I guess. Anyway this is solved.
