### ISSUE TITLE
5 player game problem

### ISSUE THREAD

**Issue by hauyinyan** [GreyWolfDev/Werewolf#291]
At the start of a game (in chaos mode), there are 5 people and there are 2 wolves (there is no GA)
In day 1, the werewolf kills a mason and the game ends......
The VG can't do anything in this game and simply lose

**Comment by joshkurien** [comment]
You chose chaos mode mate.. it inherently means that there is no balancing, and is totally random allocation of roles. 
Next time, try normal mode, it's chaos. But with balance
