### ISSUE TITLE
Wrong translation

### ISSUE THREAD

**Issue by St1f1er** [GreyWolfDev/Werewolf#294]
https://github.com/GreyWolfDev/Werewolf/blob/434558b77d404bae63c148150e397d48196beb13/Werewolf%20for%20Telegram/Languages/Russian.xml#L505

The Mason translated as Bricklayer

**Comment by Olgabrezel** [comment]
Hey there, please don't open issues or pull requests for translation reasons :) The russian file is not closed, so everyone can edit it. If you want to improve the translation, inform yourself at t.me/werewolftranslation and when you're done, you can for example pm me on telegram (@Olgabrezel). Thank you :)
