### ISSUE TITLE
First night timer

### ISSUE THREAD

**Issue by badgercl** [GreyWolfDev/Werewolf#316]
We have noticed that even when we have configured the Day and Night Timer using the /config@werewolfbot command, they are not considered the first night when there are either cupid, doppelgänger or wild child. If any of them is present in a game, the timer is always set for 120 seconds. That mean, players have hints about the presence of any of those roles. In small games it's pretty easy to identify players with the roles mentioned above and the gameplay is affected since not everyone is aware of this hidden rule.

We would like to suggest that the first night should be always a fixed time. I agree that 60 secs might be too short, but maybe 90 or 120 secs, regardless the playing roles.

Thanks!

**Comment by renyhp** [comment]
That is intended, because we want those roles to accurately choose. We will consider changing this behaviour.
