### ISSUE TITLE
Allow admin to change minimum players in config

### ISSUE THREAD

**Issue by cozyplanes** [GreyWolfDev/Werewolf#317]
Sorry if it is repost, new here
Can you team make a option in config to change minimum players?

**Comment by Olgabrezel** [comment]
What "stages" do you want to be configable for minimum player count?

**Comment by cozyplanes** [comment]
i mean the /startgame requires 5 players. maybe make that changeable

**Comment by Olgabrezel** [comment]
I know, but what "levels" or "stages" do you expect? 10? 20? 30? 35?!

Cause less than 5 won't be possible and actually, why would group admins forbid small games?

**Comment by parabola949** [comment]
I think its about people not wanting a game to start until 20 people join however it does not solve much of an issue as the game joining sequence will still timeout and the game will be cancelled. 

To really benefit from having a larger minimum for a game to start you would to disable games timeing out during the join phase and starting

**Comment by cozyplanes** [comment]
@Olgabrezel oh, i wanted to start from the level of 3 or 4, but if that is impossible, still making admin tweak the settings will be nice
