### ISSUE TITLE
Got investigation result even when the user was killed by gunner

### ISSUE THREAD

**Issue by badgercl** [GreyWolfDev/Werewolf#318]
We just had a game where a player was incorrectly notified about the detective research results:

1. The game included an alpha, a gunner and a detective. 
2. During Day phase the detective chose to investigate the alpha wolf player (not knowing that yet).
3. At the same phase, the gunner chose the detective player to kill.
4. At the end of the phase, the detective was killed, but the bot nevertheless revealed the just killed detective with the investigation results.

We believe this is a bug since the killed seers, fools and sorcerers do not know the results of their visions and the detective should follow the same rule.

<img width="484" alt="screen shot 2017-10-11 at 12 00 32 pm" src="https://user-images.githubusercontent.com/4398862/31449314-efc4cd6e-ae7c-11e7-8426-a842f5a57295.png">

<img width="441" alt="screen shot 2017-10-11 at 11 57 39 am" src="https://user-images.githubusercontent.com/4398862/31449322-f489712e-ae7c-11e7-91c3-679cd26fad9f.png">

**Comment by Olgabrezel** [comment]
Fixed on beta :) Thanks for the report!
