### ISSUE TITLE
Severe lagging, option panel problems and more

### ISSUE THREAD

**Issue by lynnexoxo** [GreyWolfDev/Werewolf#319]
The werewolfbot is severely lagging and when options are available, it does not allow me to pick a second option and froze when it’s supposed to be available. Worse when i reopen telegram, it picks something else than the option i chose. Furthermore,  the option panel is still stuck within the werewolf moderator, hope you’ll fix these problems soon thanks

**Comment by dllz** [comment]
1. Telegram is having issues with our Tokens and so thats what is causing the lag, it not replying to messages and leaving the menus open when they should close. 
There is nothing we can do to fix it right now.
