### ISSUE TITLE
As a suggestion.Change the percentage of attack Based on the type of wolf When it is alone

### ISSUE THREAD

**Issue by hasan120** [GreyWolfDev/Werewolf#320]
As a suggestion.Change the percentage of attack Based on the type of wolf When it is alone
For example
Wolf cubs When it is alone More chance for Eat sheriff and serial killer

**Comment by Olgabrezel** [comment]
Well, the town hunter has chances depending on the number of roles. I believe for other roles, such as the serial killer, the current percentages are fine.
