### ISSUE TITLE
Mysterious no Name player

### ISSUE THREAD

**Issue by SitiSchu** [GreyWolfDev/Werewolf#322]
Recently in our games a "Player" was listed that had no name. But in the group there is no user with a non existent name. 
![ss 2017-11-01 at 02 36 57](https://user-images.githubusercontent.com/18517178/32256187-d4c1be82-bead-11e7-8c4e-90c473693452.png)
![ss 2017-11-01 at 02 36 33](https://user-images.githubusercontent.com/18517178/32256191-dbc3293c-bead-11e7-9df2-7905efe67896.png)

**Comment by jeffffc** [comment]
Names in our bot are cached when people join a game, probably he used the empty name when he joined and then changed. We may help you find out who he/she is (no guarantee) but please join @werewolfsupport on telegram and forward the related messages there.

**Comment by mr-invisible-guy** [comment]
Not a bug.

I had an invisible unicode character as my name and changed my name throughout the game.

Proof: http://picul.de/view/HrZ / http://picul.de/view/HrW

**Comment by SitiSchu** [comment]
There was nobody in the group with such name even before the bot was added.
