### ISSUE TITLE
Not voting penalty shows user id

### ISSUE THREAD

**Issue by SitiSchu** [GreyWolfDev/Werewolf#323]
When the bot displays `IdleCount` for not voting twice the userid is shown in paranthesis behind the actual (working) mention. Standard mode.
![ss 2017-11-01 at 02 38 32](https://user-images.githubusercontent.com/18517178/32256287-79830d7c-beae-11e7-887d-47a06d777b8d.png)

**Comment by jeffffc** [comment]
ID are shown deliberately (even before the bots being able to send inline mention) for groups to use the id to penalize AFK users, especially when people change name often. For example in our official group (@werewolfgame), a temporary ban will be set upon at least 2 idles within 24 hours.

**Comment by SitiSchu** [comment]
Good to know no. 2 ^^
