### ISSUE TITLE
Calculate Wolfcub as single Wolf, if there is no DG/WC/Traitor/Cursed/other wolf

### ISSUE THREAD

**Issue by saalij** [GreyWolfDev/Werewolf#328]
Some games seems to be unbalanced, because there is a wolfcub, which is calculated higher than a normal single wolf, but there isn't (and will not be) somebody to help him/follow hi way. Maybe this could be calculated in another way.

**Comment by Olgabrezel** [comment]
Good one. Maybe I'm gonna make a pull request about this soon
