### ISSUE TITLE
Error 502 - Bad gateway

### ISSUE THREAD

**Issue by pablosantiago95** [GreyWolfDev/Werewolf#334]
When I want to check my stats of the game, or the group stats, it's impossible. It says it's a host error, the web server reported a bad gateway error and try again in a few minutes. I think the page isn't working 2 weeks ago. I don't know if somebody has reported also. I would like to check my stats, and know if I've reached the 500 games played.

**Comment by Olgabrezel** [comment]
We are aware of that. You can check your stats by typing "@werewolfbot " in any chat (without the quotations) and hitting the appearing stats button.

**Comment by Olgabrezel** [comment]
Please leave this issue open anyways, we will close it when the website is back (which we sadly can't tell when it will be the case)

**Comment by pablosantiago95** [comment]
Thanks! I hope the website can come back soon and the problem solved. I didn't know that command, very good to know new "tricks", although we can't see the group stats.

**Comment by jeffffc** [comment]
http://tgwerewolf.com The website is working now, please try again!
