### ISSUE TITLE
Assassin wins when her lover dies for afk

### ISSUE THREAD

**Issue by jesusjda** [GreyWolfDev/Werewolf#363]
There were 4 players in the game
Assassin, villager, Oracle and Cupido

Assassin was in love with cupido but cupido was AFK

Cupido was eliminated because of didn't vote on two rounds. but the assasin didn't die

The assassin was able to kill next night and win the 1 vs 1.

Btw, do you accept free help on the bot?

**Comment by parabola949** [comment]
This is not a bug.  It's not fair to lovers if one person goes AFK, so when someone dies of AFK the lover is never killed.  Working as designed.

**Comment by parabola949** [comment]
Also, yes, we accept pull requests
