### ISSUE TITLE
Feature Request: New command to disallow a user not to join game in the group(a user black list for group)

### ISSUE THREAD

**Issue by Cojad** [GreyWolfDev/Werewolf#374]
I'm t.me/twWolf Creator.
I recently discovered some player using client TG bot to join game and play automatically by bot.
This is destroying whole group gaming experience. Since werewolfbot no longer need user to use /join to join game. 

I have to use /smite to kill that user from auto join the game until he found the log that he was smite by me. So he realised I do not allow bot playing. And stop all of that.

But I found out a Developer can simply get start=xxxxxxxxx parameter to join game easily even if his account is forbid to post message in group. Group admin has no effect way to limit a user to join game. Even if a user is completed ban by group, he still able to use second account in group to get start parameter to join game with banned user. This has become a flaw. because a public super group, he can always use a second or third account to get the start parameter and join game with primary account and I can do nothing about it.

So I purpose we should have a blacklist command to able let admin easily limit user from join the game. It will be even better to also able to temp blacklist a user with due date like 
/ban 2018-06-30 1800+8
+8 to specifiy timezome GMT+8 
so that user will not able to play until 30 Jun, 1800 GMT+8 time.

**Comment by chrizrobert** [comment]
I believe that this can be handled through muting the user - when accepting a join request, The werewolf bot also checks if they are a member of the group. This setting would be group specific.

https://github.com/GreyWolfDev/Werewolf/blob/4c6f695f80f4f0bc00c57e59f65eb1ddf9e1c245/Werewolf%20for%20Telegram/Werewolf%20Control/Commands/GeneralCommands.cs#L278

**Comment by Cojad** [comment]
So far, wererwolf bot only check left or kicked. I suggest to add check if user has permission of "send message" in group.

**Comment by Olgabrezel** [comment]
>Even if a user is completed ban by group, he still able to use second account in group to get start parameter to join game with banned user.

Well, untrue. The banned account won't be able to join. If it can join, and you have prove of that, please provide it (come to [the support group](https://t.me/greywolfsupport))

>I suggest to add check if user has permission of "send message" in group.

For what reason? If you don't want them to play, simply ban them from the group.

About the feature request: This will quite surely not come. Why should we bother storing banned users per group in the database - if you want to forbid users to play in a group (temporarily), ban them (temporarily). That's what we've always done in the official groups and it works well.
