### ISSUE TITLE
The Rich

### ISSUE THREAD

**Issue by Abs3ntX** [GreyWolfDev/Werewolf#382]
He's an incredibly powerful person, more than the mayor! a the very start of the game he can choose to which team he will go, team villagers or team werewolf, he will get a random role of the team chosen, but if he chooses to go to the villager team he has 20% of possibility that the wolves get confused about their target and decide to attack him, if he chooses to go with the werewolf team at the end of the lynch phase if nobody gets lynched he will die.

**Comment by Olgabrezel** [comment]
Please submit role suggestions by commenting at #141, not by opening new issues. Closing this.
