### ISSUE TITLE
sorcerer can't see lykan

### ISSUE THREAD

**Issue by DerUser** [GreyWolfDev/Werewolf#384]
In a game just now, I was the lykan and my sorcerer got me killed by lynch, because he thought I was not a wolf. This is rather problematic.

**Comment by Olgabrezel** [comment]
This is indeed intended. Sorcerer will not see lycan as wolf, because else lycan would be too harmful to the village. Sorcerer won't see wolf man as wolf either (though this is something that could be argued). Anyway, that was intended (Reference https://t.me/greywolfdev/1070)
