### ISSUE TITLE
[Request] about GIF in game.

### ISSUE THREAD

**Issue by KaiVetieno** [GreyWolfDev/Werewolf#39]
It'd be nice if we can disable GIF and/or change it to other set of GIF when playing other settings like Mafia.

**Comment by RaptDept** [comment]
I'm a bit afraid to imagine what this would do on the Furry NSFW language pack...

**Comment by SilasSit** [comment]
Then make it NSFW if they wish, isn't it? I think the translaters should choose gifs and the group choose if they enable the gifs

**Comment by renyhp** [comment]
You can now set a custom gif set by donating.
