### ISSUE TITLE
Enhancement - a waitlist command

### ISSUE THREAD

**Issue by Poolitzer** [GreyWolfDev/Werewolf#392]
/waitlist could show you who joined the waitlist without having to start the game.

**Comment by Olgabrezel** [comment]
What is the use of that? Why would you need that?

**Comment by Olfi01** [comment]
Not really a useful command, indeed.

**Comment by Olgabrezel** [comment]
Well... I see literally no use in that, so... * shrug *
Feel free to still comment on this if there is a meaningful usecase, @Poolitzer
