### ISSUE TITLE
[Feature request] Allow unlimited extend time

### ISSUE THREAD

**Issue by stkw0** [GreyWolfDev/Werewolf#394]
Currently it seems that the maximum extend time is 300 seconds. It will be useful to be able to set an arbitrary number or seconds or disable this timeout and instead force the start manually when all the players are ready.

**Comment by Olgabrezel** [comment]
Double. There is already #17. The problem with all of those ideas is, the nodes can't handle so many games at once. And the number of games at the same time would increase drastically if they wouldn't be abandoned out of inactivity.
