### ISSUE TITLE
Bug reporting: Half-thief not able to steal on 2nd night if it is a doppeled half thief

### ISSUE THREAD

**Issue by geromeang** [GreyWolfDev/Werewolf#397]
Kunoichi Skye:
1. I doppeled thief
2. Thief died, now I'm thief
3. But since its half-thief, a thief can only steal on first night
4. Hence I can't steal anyone on 2nd night
5. I autolose

**Comment by Olgabrezel** [comment]
LOL. That is an interesting case we need to think about. Thank you for reporting this.

**Comment by Olgabrezel** [comment]
Thanks for the report, the problem got fixed in 368645d :)
