### ISSUE TITLE
snow wolf

### ISSUE THREAD

**Issue by shahriarkarimzadeh** [GreyWolfDev/Werewolf#436]
wolf's can eat the snow wolf

**Comment by Olfi01** [comment]
Can you please be more specific? What exactly happened? Is that always possible? How? Snow wolf should not appear in the list of people to eat.

**Comment by Olgabrezel** [comment]
Yup, it would be cool if you could provide a screenshot or a message link to a public group where that happened (either here on github or [join the support group on telegram](https://t.me/werewolfsupport) and tag me (@Olgabrezel))

**Comment by Olgabrezel** [comment]
I'm closing this issue as it is older than 2 years and no clarification was given. If this or a similar problem should happen again, feel free to open a new issue with a full description of the problem.
