### ISSUE TITLE
Update SQL generation script

### ISSUE THREAD

**Issue by Olfi01** [GreyWolfDev/Werewolf#441]
https://pastebin.com/hL8NK0vn
This is the currently working schema that I generated from my own debug instance. This could be included instead of the old script.

**Comment by Olfi01** [comment]
To really use the bot you'd still have to add entries to BotStatus however.
(not to mention the API keys in the registry and the gif ids in Settings.cs)

**Comment by Olgabrezel** [comment]
It's updated now
