### ISSUE TITLE
Thief stealing from Beauty not getting notified

### ISSUE THREAD

**Issue by Clumi** [GreyWolfDev/Werewolf#442]
In my last game as thief, I tried to steal from the beauty. It only said "Choice accepted" and no further notification. But when we lynched the beauty, I died out of love as well. So I think you forgot to add the notification. If I can give more info, please let me know.

**Comment by Olfi01** [comment]
This is not Blackwolf bot. The role beauty does not exist here.

**Comment by Jummey** [comment]
Thanks for the info (I put it on the list) but please use black wws support group next time as the code is currently closed source 
Sorry :joy::joy:
