### ISSUE TITLE
IsGroupAdmin could cache its return value

### ISSUE THREAD

**Issue by mauguignard** [GreyWolfDev/Werewolf#450]
Every time a user uses a command with  GroupAdminOnly = true attribute, the bot currently needs to check if the user is an administrator of the group in question. Since Group Admins normally dont't change very frequently, it could make sense to use some form of TTL cache to cache the result of IsGroupAdmin and avoid an extra API request each time. This could improve the performance especially when the bot is very busy. The performance could even be improved further by using the Telegram Bot API's getChatAdministrators method to query for all admins in a group at once.

**Comment by Olgabrezel** [comment]
Did you notice those group admin only commands being especially slow? Or why do you think such a cache would be needed?

**Comment by Olgabrezel** [comment]
Fixed in fdad45ec.
