### ISSUE TITLE
moving stats from one account to another

### ISSUE THREAD

**Issue by sinamcr7** [GreyWolfDev/Werewolf#457]
hello
my main account got permanently reported for an unknown reason and it became rep chat every time for half an hour after sending a limited number of messages
so I got stuck in this situation and I found no way to fix it
then I decided to ask you if there is a way to move my stats from that account to a new account?

**Comment by Olgabrezel** [comment]
Please come to [@werewolfsupport](https://t.me/werewolfsupport) on telegram and we'll look if we can help you :)
