### ISSUE TITLE
can not compile in visual studio !!

### ISSUE THREAD

**Issue by RezaHadavandi** [GreyWolfDev/Werewolf#487]
what version recommended visual studio ?
what is recommended package for install and run in visual studio?

**Comment by Olgabrezel** [comment]
Please be more specific. "can not compile in visual studio !!" doesn't tell us anything about your problem. Visual Studio 2017 and 2019 are working for me.

**Comment by Olgabrezel** [comment]
I'm closing this issue as it is older than a year and no clarification was given. If this or a similar problem should happen again, feel free to open a new issue with a full description of the problem.
