### ISSUE TITLE
The bot doesn’t always save changes in /config

### ISSUE THREAD

**Issue by Flowiee** [GreyWolfDev/Werewolf#500]
Sometimes you have to press more times the buttons in /config menu and also if it changes page it still doesn’t save the new value, like, when you change "game mode" setting and for Full Thief Setting the bot won’t accept the changes.. 

For change mode we found that works if you press MORE times the page...

For game mode we have two Chat ID that had this issue:
-1001122689401
-1001212883210

**Comment by azuwlaa** [comment]
> Sometimes you have to press more times the buttons in /config menu and also if it changes page it still doesn’t save the new value, like, when you change "game mode" setting and for Full Thief Setting the bot won’t accept the changes..
Whenever a game is started with startgame value is random to Normal game to chaos /config Players choice doesn't change
> 
> For change mode we found that works if you press MORE times the page...
> 
> For game mode we have two Chat ID that had this issue:
> -1001122689401
> -1001212883210

**Comment by Flowiee** [comment]
No bug.

They enabled "Random Mode" on "Game Mechanics" and it indeed didn’t take care of the config..
