### ISSUE TITLE
The Bot won't let me in the game

### ISSUE THREAD

**Issue by perruxo** [GreyWolfDev/Werewolf#513]
Guys my group is starting the game and somehow i press start but the but doesn't respond. 
Does anyone knows how to fix it?

**Comment by perruxo** [comment]
actually now doesn't respect any command i do, not even /stats. 
I think it happenned after I tried to enter one round before 10 seconds it started.....and at the same time i clicked to join it, the round started and since then i'm not able to do anything else....

**Comment by Flowiee** [comment]
Join @werewolfsupport group on Telegram, if you are banned the bot will tell you it when you will join.

**Comment by Olgabrezel** [comment]
^ What Flowiee said
