### ISSUE TITLE
Add a string for Arsonist for the first turn/when there aren’t doused houses

### ISSUE THREAD

**Issue by Flowiee** [GreyWolfDev/Werewolf#526]
The current string says: "Do you want to douse another house or do you want to see all doused houses burn?"

But if there aren’t other houses before it doesn’t make sense.

**Comment by Flowiee** [comment]
Also, it would be good to have the list of players that are already doused so you will know how many players you will burn (and if GA acted, because checking it by checking how many buttons there are is hard)

**Comment by Olgabrezel** [comment]
This has been fixed in the meantime :​)
