### ISSUE TITLE
change http links to https 

### ISSUE THREAD

**Issue by gheysar-official** [GreyWolfDev/Werewolf#538]
all external links in ww bot are http. when i opened a group stats webpage i got 503 error and i changed http to https, that works well. after that my chrome redirect all http requests to https. 

its better to to change links or redirect all http traffics to https

**Comment by Olgabrezel** [comment]
@gheysar-official Oh, wow. You (or someone else) can freely open a pull request for this (and earn some developer achievement? :D). Just changing the links to HTTPS should be good.

**Comment by gheysar-official** [comment]
thx bro :D
