### ISSUE TITLE
Bot does not respond 

### ISSUE THREAD

**Issue by batgirlx** [GreyWolfDev/Werewolf#542]
I’ve been trying to join the game or start it and the bot just ignores me, I’ve sent /help /config /start in the private chat and it’s as if I wasn’t sending anything. It does absolutely nothing, everybody else in my group can play just fine

**Comment by Olgabrezel** [comment]
@batgirlx Please join the support group on telegram (https://t.me/werewolfsupport) to check if you got banned from the bot somehow :)
