### ISSUE TITLE
Lovers didn’t receive any message

### ISSUE THREAD

**Issue by negindelav** [GreyWolfDev/Werewolf#543]
Lovers didn’t receive any message  from bot that informs them they begin lovers 
idk this is a ww moderator  issue or telegram 
it happens to me just one time

**Comment by Olgabrezel** [comment]
Without further information we can barely conclude why this happened... If it only happens with a specific language mode set, for example, we could look into that. But this way, I'm going to assume it was a telegram bug. If you find anything that could be helpful regarding this, feel free to step by [@greywolfsupport](https://t.me/GreyWolfSupport) on telegram :)
