### ISSUE TITLE
this role will balance the game

### ISSUE THREAD

**Issue by pikaruto** [GreyWolfDev/Werewolf#544]
If the cult stays until the late game. It is so hard to win, especially when CH died. So i How if you add a new role : squire (he is like appseer, will become CH after Ch dies. So the village team still had a chance to ein against cult if the Ch dies. But if you don't really want to add new role, why don't you lower the succesfull percentage of cultist. Thank you.

**Comment by Flowiee** [comment]
To suggest new roles look at #141
