### ISSUE TITLE
Thief and skipped wolf bug

### ISSUE THREAD

**Issue by ifarshidgh** [GreyWolfDev/Werewolf#545]
I tried 17 times to steal the role of a wolf who was skipping at the same time and all the times i failed, its possibility is about 0.000008 and i guess it's a bug.

**Comment by Olgabrezel** [comment]
@ifarshidgh No, it is not a bug, the full thief is unable to steal the wolf role. Refer to https://t.me/greywolfdev/1134

*The Full-Game-Thief can NOT steal a Werewolf, Wolf Cub, Alpha Wolf, Lycan or Cultist - Trying to steal one of these roles will always result in failure.*
