### ISSUE TITLE
Grouplist is disable in my country Indonesia

### ISSUE THREAD

**Issue by Wizzy11** [GreyWolfDev/Werewolf#546]
Why Grouplist is disable

**Comment by Flowiee** [comment]
@Wizzy11 It doesn’t depend on country, the grouplist has problems so it has been globally disabled

**Comment by Wizzy11** [comment]
Where can I got the list of any group order by language? With group username? Which top ten only 
like in grouplist @somegroup

**Comment by Olgabrezel** [comment]
You should now be able to get the grouplist again in [@werewolfbetabot](https://t.me/werewolfbetabot)
