### ISSUE TITLE
Alpha Biting problem

### ISSUE THREAD

**Issue by amirbarfi** [GreyWolfDev/Werewolf#550]
When I was an alpha wolf and I was offline. My werewolf teammate just suggested to eat a Villager and out of nowhere there was a message that I have infected that Vg and this was a serious problem. Because for infecting someone you need the alpha wolf to choose the victem.

**Comment by Olgabrezel** [comment]
@amirbarfi This is actually intended behavior and not a **serious** problem :)
If the alpha is alive, they can infect the victim, no matter if the alpha actually chose that victim or not.

**Comment by amirbarfi** [comment]
Ok✌🏿

**Comment by amirbarfi** [comment]
I'm sorry to ask this but I don't know any admins of the moderator to ask
about achievements.
I have 83 achvs and the real question is which achvs R now inactive.
And what is the percentage to infect SK.
And the last question is that para is still playing with secret acc so hai
der is active or not.
TnQ

**Comment by Olgabrezel** [comment]
@amirbarfi Feel free to come to [our support groups on telegram](https://t.me/greywolfsupport) to get such questions answered :)
