### ISSUE TITLE
Support ananymous mode 

### ISSUE THREAD

**Issue by sajadGheysar** [GreyWolfDev/Werewolf#551]
Just tell exit ananymous mode to use this command instead of this
![IMG_20201004_123422_862.jpg](https://user-images.githubusercontent.com/54141473/95011492-f1892200-063d-11eb-9413-4a30d0e29750.jpg)

**Comment by OlgabrezelPrivate** [comment]
This has in theory been fixed in bdbe6c5, but is currently not working anymore, because the update is being ignored. 
Will leave it open until it's resolved again.
