### ISSUE TITLE
Bug in The Fool role

### ISSUE THREAD

**Issue by mojtaba1107** [GreyWolfDev/Werewolf#555]
When I was Fool, I saw one of the players' role, The wolfman.
I think this is bug because This show us that I am Fool and I think bot should make me believe I am Seer...

**Comment by Flowiee** [comment]
@mojtaba1107 The fact that fool can see WolfMan is a FEATURE.

Fool can see: WolfMan and Traitor and it’s a feature because it helps to understand what is the original role :)
