### ISSUE TITLE
Making a country map with a definite color will be on-site according to the number of players and the average status

### ISSUE THREAD

**Issue by qokab** [GreyWolfDev/Werewolf#562]

**Comment by Olgabrezel** [comment]
I do not understand what this means. Can you please clarify?

**Comment by qokab** [comment]
i wanted to explain about building some global state map showing where players are from, and categorizing them with color or something else bye their average stats

**Comment by Datpaitoon** [comment]
@alex22200r

**Comment by OlgabrezelPrivate** [comment]
Well, I think we can close this: What you're asking for can't be done as we can't *know* where players are from. And the player's language setting is not really a good indicator for this, as most players will have "English" set as their default.
Also, this stats page would surely be faked by botting users like all other global stats anyway, so what's the point 🤷‍♂️
