### ISSUE TITLE
Issue with language

### ISSUE THREAD

**Issue by mespinosa96** [GreyWolfDev/Werewolf#569]
Hello,
till yesterday the bot was working perfectly (very well made, btw). But today no matter what language I set, strange symbols (language) appear (not in the start message, but in following ones). What can be the problem? We have tried restarting the bot to no avail.
sorry for the trouble, 
marcos

**Comment by Olgabrezel** [comment]
Hmmmm. *Yesterday* it worked.
*Today* it's weird.
Perhaps, *tomorrow* it may be normal again.

Is there anything *special* about today's date, I wonder? :)

<details>
<summary>I'm not entirely sure...</summary>


https://user-images.githubusercontent.com/24510817/113248344-0ed13d00-92bd-11eb-91f7-ea8eaa8ea714.mp4

</details>
