### ISSUE TITLE
log channel for werewolf bot

### ISSUE THREAD

**Issue by qokab** [GreyWolfDev/Werewolf#579]
create log channel for wwbot and add /config command and which admin used it, also add: they changed settings or not and if they changed something show what and in which part, also I think it's better to send game end message to log channel. and canceled games

**Comment by Olgabrezel** [comment]
Duplicate, please head to #540. :​)

**Comment by qokab** [comment]
oh sorry didn't saw that xd ,can anyone write it and request in github?
