### ISSUE TITLE
Werewolf game - language problem

### ISSUE THREAD

**Issue by aphroditekaos** [GreyWolfDev/Werewolf#602]
Hello,
I am a admin of the group @kaoscularr and i can‘t change the language of the „werewolf“ game.
It‘s in english and i want to change the language to „turkish“.
I did everything to change it and i followed all the instructions but it‘s still in english.
Can someone help me please?

**Comment by hojjat-gh78** [comment]
hello ,
send the command /config to the group

**Comment by OlgabrezelPrivate** [comment]
Hi, I'm closing this since you haven't replied anymore.
If you have any issues with the bot, feel free to come to [@greywolfsupport](https://t.me/GreyWolfSupport) on telegram and the people there will help you out :)
