### ISSUE TITLE
There are a couple game timer configurations planned.  One will be where an admin of the group can advance the timer, the other will be a "real time" game, where each day / lynch / night is a full 24 hour period.

### ISSUE THREAD

**Issue by pranusit** [GreyWolfDev/Werewolf#606]
There are a couple game timer configurations planned.  One will be where an admin of the group can advance the timer, the other will be a "real time" game, where each day / lynch / night is a full 24 hour period.

However - simply having the game not advance until everyone has made their choice will lead to issues, for instance if a player just.. stops playing.  Besides the fact that it would hang the game for everyone, I wouldn't be able to update the node without killing the game.

_Originally posted by @parabola949 in https://github.com/GreyWolfDev/Werewolf/issues/17#issuecomment-228771184_

**Comment by pranusit** [comment]
https://github.com/GreyWolfDev/Werewolf/issues/605

**Comment by Olgabrezel** [comment]
I doubt it will ever happen. For the reason that Para stated and the fact that there would probably be just way too many games at once. Anyway, since you just opened a bunch of pointless issues and issue #17 is still open, I'm going to close this.
