### ISSUE TITLE
any Isssue

### ISSUE THREAD

**Issue by aminsato** [GreyWolfDev/Werewolf#641]
Hello guys 
I'm a C# programmer
Is there any problem that I can handle it??

**Comment by OlgabrezelPrivate** [comment]
Did you... open an issue to ask for issues?
If you know of a problem you'd like to fix, feel free to. You may ask in  [@greywolfsupport](https://t.me/greywolfsupport) first, to make sure it really is something that we would accept a pull request for.
But we don't have an internal list of problems other than in the issues here on GItHub.
